### ISSUE TITLE
When submitting name and idea, the name is displayed as the idea and the idea disappears

### ISSUE THREAD

**Issue by LukeBiddle** [JaredPage/worst-idea-today#1]
Seems like the Name text field is being treated as the idea. This is bad for our customers and should be remedied ASAP.

**Comment by JaredPage** [comment]
Thanks LukeBiddle. Here at worst-idea-today we value our customers and as such a fix for the naming system will be released by the end of the week. Keep an eye out !

**Comment by LukeBiddle** [comment]
I am overwhelmingly happy with the provided fix, send my regards to the talented developers on your team.
