### ISSUE TITLE
No downvote button anywhere

### ISSUE THREAD

**Issue by LukeBiddle** [JaredPage/worst-idea-today#3]
Downvoting is a key feature of the website, and the fact that it is entirely absent is detrimental to the end user. This feature is definitely required for today's ideas, and I think there should be a discussion on whether or not a user is allowed to downvote an archived idea.

**Comment by JaredPage** [comment]
Good news LukeBiddle ! 
The downvote button is making a triumphant return to worst-idea-today. 
In the update coming out this week, the downvote button will be back bigger and better than ever.

**Comment by JaredPage** [comment]
LukeBiddle, I believe this issue is now closed with the advent of the stylish new downvote button.
